name: Test & build

on:
  push:
    branches:
      - "*"

jobs:
  test-and-build:
    name: Test & build
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
      checks: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: yarn --pure-lockfile

      - name: Codegen
        run: yarn codegen

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Check for partner API breaking changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:src/graphql/schemas/partner.gql"
          github-token: ${{ github.token }}

      - name: Check for internal API breaking changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:src/graphql/schemas/internal.gql"
          github-token: ${{ github.token }}

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.26.2 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Push partner to federation
        run: rover subgraph publish test-o7a8t@current --schema=src/graphql/schemas/partner.gql --name api-starter-kit --routing-url http://products.prod.svc.cluster.local:4001/graphql
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY_PARTNER }}

      - name: Push internal to federation
        run: rover subgraph publish internal-zf12etf@current --schema=src/graphql/schemas/internal.gql --name api-starter-kit --routing-url http://products.prod.svc.cluster.local:4001/graphql
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY_INTERNAL }}
